### PR TITLE
Better handling of "No newline at end of file" marker

### LINKED ISSUE #4: "No newline at end of file" can be non-trailing
Here is an example patch that fails to parse:
```diff
--- a/test.txt
+++ b/test.txt
@@ -1,4 +1,5 @@
 python
 eggy
 hamster
-guido
\ No newline at end of file
+
+hello
\ No newline at end of file
```

From my understanding, this indicator is added after the line if the line is last and has no `\n` character at the end.

Now this indicator is modeled as a boolean flag in the patch, but actually there should be two such flags, as we have two last lines: one before the patch and one after the patch.

### PR DESCRIPTION
**Pull request by romamik**
Fixes #4.

Now the parser checks for every line if it is followed by the "No newline at end of file" line, and saves it with the line. This flag is later used to determine this status for the hunk and then for the file. 

Also, I renamed the flag to `missing_newline` as for me, it was hard to wrap my head around the inverted logic of the previous flag. I know that the original marker has negated meaning and that is the main source of confusion, but having variables that are opposite to the marker present in file was an additional source of confusion to me.

### CODE REVIEW

**Comment by sourcefrog** [comment]
I just hit this in testing cargo-mutants; it would be nice to merge and release a fix.

**Comment by vrmiguel** [comment]
@romamik I added a commit to fix a git conflict, hope you don't mind

File: src/ast.rs [hunk 1]
```diff
@@ -265,24 +266,60 @@ impl fmt::Display for Range {
     }
 }
 
-/// A line of the old file, new file, or both
-#[derive(Debug, Clone, Eq, PartialEq)]
-pub enum Line<'a> {
+#[derive(Debug, Clone, Copy, PartialEq, Eq)]
+pub enum LineKind {
```
Comment (vrmiguel) [inline src/ast.rs]: This would be a pretty big breaking change, do you think it's worth it?

I agree with adding `old/new_missing_newline` to `Patch` and `Hunk`, but I'm not seeing the value of tracking `missing_newline` per line, since mid-hunk "no newline" indicators don't seem to be a thing

@psandana @sourcefrog since this is being tracked in https://github.com/sourcefrog/cargo-mutants/pull/507, what are your thoughts on this change?

Comment (romamik) [reply src/ast.rs]: I do not remember this in details, but I think it was just easier to do it this way. I believe it was something like this: at the moment we parse lines patches and hunks do not exist/are not accessible, so there is no place to store this flag other than line. 

As for commits, please feel free to do anything you want with this pull request. Good to see some movement here.

Comment (sourcefrog) [reply src/ast.rs]: Hey,

I agree this seems a bit strange where it is at the moment. You can't have a missing newline within a hunk, it can really only be at the end of the overall file, or not (for each of the old and new files.)

I guess it depends a bit on whether this crate wants to represent something like 
1. "the AST of the diff" (which can have "missing newline" markers), or 
2. "the sequence of lines implied by the diff"

I think of it as more like the first although it's definitely useful to be able to recover the second.

That to me implies putting two markers in the `Patch`.

Separately regarding the change of `Line` enum to a `LineKind`, I don't care too much about the API break, I think either having the string inside the enum or outside would be OK.

Comment (whitty) [reply src/ast.rs]: > I do not remember this in details, but I think it was just easier to do it this way. I believe it was something like this: at the moment we parse lines patches and hunks do not exist/are not accessible, so there is no place to store this flag other than line.

Is this a factor of the parsing elements being the same as the (public) AST elements?  #3 (though it may be incomplete) moves to an [internal "parsing-oriented" `enum`](https://github.com/gitpatch-rs/gitpatch/pull/3/files#diff-4a04259da480a6b794a2e947e4cc03eff4d1aa9330836f5b91cac68c5398193fR307) before moving the appropriate ones to the final `enum Line` at the end.

This somewhat gets at the difference between "AST of diff" (ast.rs) and "sequence of lines" (parser.rs).

If parser.rs has its own `Line`-like enum we avoid the API breakage.

File: examples/apply.rs [hunk 2]
```diff
@@ -1,25 +1,32 @@
...
+                }
+                LineKind::Remove => {}
             }
         }
     }
-    out.join("\n")
+    if need_new_line {
+        out.push("");
+    }
+    out.join("")
```
Comment (sourcefrog) [inline examples/apply.rs]: I'm confused how these lines work together to get a newline. Pushing `""` would produce a final newline only if you were to join with `\n`, but you don't?

File: src/ast.rs [hunk 3]
```diff
@@ -12,13 +12,12 @@ pub struct Patch<'a> {
     pub old: File<'a>,
     /// The file information of the `+` side of the diff, line prefix: `+++`
     pub new: File<'a>,
+    /// If there was a `No newline at end of file` indicator after the last line of the old version of the file
+    pub old_missing_newline: bool,
+    /// If there was a `No newline at end of file` indicator after the last line of the new version of the file
+    pub new_missing_newline: bool,
```
Comment (sourcefrog) [inline src/ast.rs:20]: I think this representation is good: clearer than individual lines having a newline or not.

File: src/ast.rs [hunk 4]
```diff
@@ -218,6 +215,10 @@ pub struct Hunk<'a> {
     pub new_range: Range,
     /// Any trailing text after the hunk's range information
     pub range_hint: &'a str,
+    /// If there was a `No newline at end of file` indicator after the last line of the old version of the hunk
+    pub old_missing_newline: bool,
+    /// If there was a `No newline at end of file` indicator after the last line of the new version of the hunk
+    pub new_missing_newline: bool,
```
Comment (sourcefrog) [inline src/ast.rs]: I think it is incongruous to have these bools on both the hunk and the whole file. To me, lacking a final newline is a property of the whole (old or new) file and not something that makes sense to set on anything but the final hunk. Can we just delete these from here?

File: src/ast.rs [hunk 5]
```diff
@@ -265,24 +266,60 @@ impl fmt::Display for Range {
...
+
+/// A line of the old file, new file, or both
+#[derive(Debug, Clone, Eq, PartialEq)]
+pub struct Line<'a> {
+    /// The kind of the line (added, removed, or context)
+    pub kind: LineKind,
+    /// The actual text of the line
+    pub content: &'a str,
+    /// If there was a `No newline at end of file` indicator after the line
+    pub missing_newline: bool,
```
Comment (sourcefrog) [inline src/ast.rs]: Again I would not add this here, at least not in the public API. On most lines it will not be meaningful.

File: src/lib.rs [hunk 6]
```diff
@@ -44,6 +44,7 @@
 //! [spec]: http://www.artima.com/weblogs/viewpost.jsp?thread=164293
 
 #![deny(unused_must_use)]
+#![allow(clippy::format_collect)]
```
Comment (sourcefrog) [inline src/lib.rs]: This is minor but it seems a little worse to allow the lint at a global level when it's only needed as a workaround in a couple cases? And at least, I'd leave the comment.

File: src/ast.rs (hunk 1 above)
Comment (sourcefrog) [reply src/ast.rs]: Leaving aside the handling of "no newline", I also don't think the change to LineKind is worth the API break.

**Review by sourcefrog — CHANGES_REQUESTED** [review]

File: src/lib.rs (hunk 6 above)
Comment (romamik) [reply src/lib.rs]: Removed this. It is not needed at all now.

File: src/ast.rs (hunk 3 above)
Comment (romamik) [reply src/ast.rs:20]: Just made a refactor. Now changes are smaller, and the public API only differs by these flags.

**Comment by romamik** [comment]
Just pushed changes that make the resulting code much closer to the current main branch state. Mostly I removed most of the changes in the public API and pushed those flags up the stack while parsing.

**Comment by romamik** [comment]
"No newline at end of file" marker (the marker) can appear after a removed line, an added line, or a context line. Depending on this, it refers to old content of the file, new content of the file, or both.

To support this, while parsing the line, I expect the optional marker after every line: the function `consume_content_line` returns tuples of `(&str, bool)` instead of just `&str` for this.

When processing each hunk, I check if there was a line with the marker attached, both for old and new content of the file.  

When processing the whole patch, I check the last hunk if it has these markers.

**Skipping trailing empty lines**
There was a bug that I had to solve after supporting this:
In the example file named "sample4.diff" there are lines that look like this:
```
+Only for testing purposes.
\ No newline at end of file

=== modified file 'modified_file'
```
Before the changes, when the marker was encountered, the parsing of the lines stopped, and then the empty line was skipped in the `patch()` function. 
But after the changes, an empty line was treated as an empty `Context` line, which is incorrect.
I decided I have to distinguish between empty lines and empty context lines (which have one space). 
After parsing the lines, I remove trailing empty lines, but not empty context lines. This allows us to still treat empty lines as empty context lines in between but prevents incorrect handling of trailing empty lines after the patch.

**Comment by sourcefrog** [comment]
> "No newline at end of file" marker (the marker) can appear after a removed line, an added line, or a context line. Depending on this, it refers to old content of the file, new content of the file, or both.
> 
> To support this, while parsing the line, I expect the optional marker after every line: the function `consume_content_line` returns tuples of `(&str, bool)` instead of just `&str` for this.

Ah I see, that makes sense.

**Review by sourcefrog — CHANGES_REQUESTED** [review]
Thanks, this looks good to me! 

Can I just ask that you also add a line to the changelog file?

@vrmiguel @whitty do you want to look too?

**Review by sourcefrog — APPROVED** [review]
